travis:
  secure:
    BINSTAR_TOKEN: K0O4SIy7ZQXdyTGlhB+GWFx+MKV86ZBoV6SheRF0D71KCmJJxe1/Tu2n1xhxjcKEIfmWK5jnC/fU5gCE551EWO4hZ56DfXSqL20ueb9Lvi74apzpWbw5Fc6FpKwFSNZC2T6UsQK4++vLhem+C+W/Bj22kT/DONrkRs6JskFnRChAcLMk3JuuAPlQDn18kot8ZdfZBwD0QmjE6n0DDX3KOSGVLIeDV3/i4Nu2NWVarZAfQ99CO10KJlOM6OLF1NsFz2zcyq5PKaOwiPQuzLoHU2AiSWx+4STb+8Tx6AVPyowp4QnUKBtQv7wHMLJ0GWFJMg6XEPvMzatfNF80phFaoZP0rbT0KdYUC8k9hDw4Eis7ZihoyU/tPhisnivv8GTcUyW7iFJOI6qNl8p9yRjzrTyg4MItjEjhfeGmcUNWJ1eX/xeVWUHov7nAD6zH0Cda/WquwfTLggj+7/1vDH08gJ9pSV2v1cXqAcVOQ33K+xS6BIIY3qBfCwY3r/ozbKSIzAva4ugFGoRKnbFBMU6o8nD/DKu2TYIucU7qztutHPyiGVJlN8nuU69e6abf7zmHUcNxmK46pt3/i3qFqv8+TJEEeOqUeUGMDYCP5sX44NSZsJUBUX6gwvOucIAx0AYuDIBx5rUz6krbfrUkNRjM7JF95rn8lnRac0s25gqQztI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
